name: insta_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.16.2 <3.0.0"

dependencies:
    cupertino_icons: ^1.0.2
    firebase_auth: ^3.3.12
    firebase_cloud_messaging_interop: ^3.0.0
    firebase_core: ^1.14.0
    firebase_storage: ^10.2.10
    flutter:
        sdk: flutter
    flutter_local_notifications: ^9.4.0
    flutter_riverpod: ^1.0.3

dev_dependencies:
    change_app_package_name: ^1.0.0
    flutter_lints: ^1.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
